### ISSUE TITLE
Prompting for Username and Password

### ISSUE THREAD

**Issue by ukiran03** [isamert/orgmdb.el#13]
After providing the API key, it is still asking for a username and password.

Username [for https://www.omdbapi.com/?t=Cure&y=1997&type=movie&plot=full&apikey=XXXXXXXX]: 
Password:

**Comment by isamert** [comment]
Interesting. What is the output of doing the following in terminal:

```
curl 'https://www.omdbapi.com/?t=Cure&y=1997&type=movie&plot=full&apikey=XXXXXXXX'
```

Does this return the correct JSON response?

**Comment by ukiran03** [comment]
Yes, the command  
``` curl 'https://www.omdbapi.com/?t=Cure&y=1997&type=movie&plot=full&apikey=XXXXXXXX' ```
 is giving the correct JSON response as intended.

**Comment by ukiran03** [comment]
Sorry, it's now working as intended.
I’m not sure what caused the issue before. Thank you for your response and for this cool package.
