### ISSUE TITLE
Do not insert `N/A`, use `user-error` when data is not found

### ISSUE THREAD

**Issue by NightMachinary** [isamert/orgmdb.el#4]
When I invoke it on `** [[https://www.wikiwand.com/en/Dumb_and_Dumber][Dumb and Dumber | Wikiwand]]`, I get:
```
:PROPERTIES:
:GENRE:    N/A
:RUNTIME:  N/A
:DIRECTOR: N/A
:IMDB-ID:  N/A
:END:
```

It would be better if it just errored.

**Comment by isamert** [comment]
This makes sense, thanks for reporting!
