### ISSUE TITLE
orgmdb--open-video assumes no spaces, no \, no ', ...

### ISSUE THREAD

**Issue by emixa-d** [isamert/orgmdb.el#8]
I noticed that this was packaged in Guix, and took a look at the source code.

More specifically, I noticed:

```
        (format "fd --absolute-path --type=file %s --glob '*%s*%s' %s"
                (concat "--extension " (s-join " --extension " orgmdb-video-file-extensions))
                it
                (if (not (s-blank? episode))
                    (concat (s-downcase episode) "*")
                  "")
                video-dir)))
```

The apparent (unverified!) issue with this code, is that it treats everything as a single string, without any quoting -- consider, e.g., the situation where 'video-dir' contains spaces (e.g. if it's `~/My Videos`) or && (`~/Videos && Other stuff`).

One method to solve this, is to quote the arguments.  However, I noticed Emacs has another method for starting processes, wherein every argument is passed as _separate_ strings, which avoids quoting issues entirely, in <https://www.gnu.org/software/emacs/manual/html_node/elisp/Asynchronous-Processes.html> and <https://www.gnu.org/software/emacs/manual/html_node/elisp/Synchronous-Processes.html> (with :command and  'args' respectively).

**Comment by isamert** [comment]
Yeah, this is completely me being undisciplined and going with the easier implementation (I created this package by simply copy pasting from my personal configuration, so it's a bit justified I hope :)). Thanks for raising an issue, I'll update it with `call-process` when I have some time. Hopefully I will do a bit more refactoring to mitigate issues like this.
