### ISSUE TITLE
Tweak fill movie detail settings

### ISSUE THREAD

**Issue by deafpolygon** [isamert/orgmdb.el#9]
Hello, it's not clear from your README how to adjust what property gets filled in with "Fill properties".   I'd like to also download the cover and attach it to the header so it can be displayed when you expand the entry. 

Is this possible?  

I'm not very familiar with LISP so any direction would be helpful.  Thanks...

I wanted to submit this as a feature request.

**Comment by isamert** [comment]
You can change the variable `orgmdb-fill-property-list`, like:

```
(setq orgmdb-fill-property-list '(genre runtime director imdb-id))
```

Possible property names are (also see the documentation of this variable by doing `C-h v orgmdb-fill-property-list RET`):

```
actors
awards
box-office
country
director
dvd
episode
genre
imdb
imdb-id
imdb-link
imdb-rating
imdb-votes
language
metacritic
metascore
play
plot
poster
production
rated
released
runtime
season
title
tomatometer
type
website
writer
year
```

Normally, you can do `M-x customize-group orgmdb RET` and you'll be presented by every customization option that a given package has. But I mistakenly marked this variable as non-customizable so it was not appearing on that screen. Fixed that, thanks for the heads up!

---

> I'd like to also download the cover and attach it to the header so it can be displayed when you expand the entry.

Currently you can't do that without writing some custom elisp. I'll take a look at that as it would be a nice addition to the package. Maybe if a property named `image` appears in `orgmdb-fill-property-list`, it automatically inserts the image as you've described. But that is going to be a little bit harder because we can't insert the image into `PROPERTIES` drawer, we need to insert it under the header without messing up what user already typed there. I'll look into this.

**Comment by deafpolygon** [comment]
Thank you!  That worked. 

> because we can't insert the image into PROPERTIES drawer

I tried doing it manually but it doesn't look right. It'd be awesome to have it in-line, though.  

I'll be happy to test it if you get around to finding a solution. I'm still trying to wrap my mind around lisp, so I'm not going to be helpful in that department yet.   good work on this package- it works very well!

**Comment by isamert** [comment]
Can you check out the latest master? Now it should be possible to attach poster images under the heading with "Fill properties" option. Just add `poster` to the `orgmdb-fill-property-list` and you are good to go. Change variable `orgmdb-poster-folder` to control where poster files are saved.

Let me know if it works for you. You may need to do `org-toggle-inline-images` to actually show images.

**Comment by deafpolygon** [comment]
Ok, I customized the orgmdb-fill-property-list, and set orgmdb-poster-folder ~/Notes/movies/covers (confirmed the path exists - `➜  Notes ls -ad ~/Notes/movies/covers 
 /home/deafpolygon/Notes/movies/covers`)  - then tried to run it.. it updates the property list with everything I added, except `poster`.  Also noticed there is an newly created buffer in my buffer list with the cover image. I'm unable to save it (says Text is read-only).  I'm also using doom emacs, if that makes a difference but it's usually pretty good about adding packages.

**Comment by isamert** [comment]
> Also noticed there is an newly created buffer in my buffer list with the cover image.

This seems to be the culprit. This buffer should vanish automatically after operation finishes successfully. Can you do `M-x toggle-debug-on-error` and re-run "Fill properties" and see if it produces an error stack trace?

**Comment by deafpolygon** [comment]
> > Also noticed there is an newly created buffer in my buffer list with the cover image.
> 
> This seems to be the culprit. This buffer should vanish automatically after operation finishes successfully. Can you do `M-x toggle-debug-on-error` and re-run "Fill properties" and see if it produces an error stack trace?

Debug on Error enabled globally
Contacting host: www.omdbapi.com:80
Contacting host: m.media-amazon.com:443
Type C-c C-c or C-c C-x to view the image as text or hex.
save-buffer: Text is read-only
Quit

**Comment by deafpolygon** [comment]
Had a thought.. I googled "Text is read-only" and saw M-x read-only-mode and toggled it on the buffer with the image.  Then performed `:w` and it was able to save the file where before, it would just say "Text is read-only" when attempting the same.  Does that help?

**Comment by isamert** [comment]
@deafpolygon Can you check out the latest master? Not quite sure what is the difference between your setup and mine that causes the issue but I guess the latest change should fix it and it's a cleaner solution anyway.

**Comment by deafpolygon** [comment]
It works!  And it looks good!  Thank you!  Cleaner solutions are good.

**Comment by deafpolygon** [comment]
Btw, I know this is nothing to do with your script (It happens when I attach an image manually) but whenever I add a new image, the others get toggled off.   Does this happen to you?

**Comment by isamert** [comment]
> It works! And it looks good! Thank you! Cleaner solutions are good.

Great! Thanks for testing it and reporting thoroughly!

> Btw, I know this is nothing to do with your script (It happens when I attach an image manually) but whenever I add a new image, the others get toggled off. Does this happen to you?

How do you add images manually? I generally use `M-x org-redisplay-inline-images` after I add an image to force display them.

**Comment by deafpolygon** [comment]
> > It works! And it looks good! Thank you! Cleaner solutions are good.
> 
> Great! Thanks for testing it and reporting thoroughly!
> 
> > Btw, I know this is nothing to do with your script (It happens when I attach an image manually) but whenever I add a new image, the others get toggled off. Does this happen to you?
> 
> How do you add images manually? I generally use `M-x org-redisplay-inline-images` after I add an image to force display them.

typing `[[~/path/to/image]]`, or using org-insert-link
